from collections.abc import Callable
from typing import Protocol

class FileObject(Protocol):
    def write(self, s: str, /) -> int: ...

def str_from_tuple(version_tuple: tuple[int, int, int] | None) -> str: ...
def attempt_import(
    module: str, function_name: str, output_str: str = ""
) -> tuple[str, bool, Callable | None]: ...
def append_dep_version(dep_name, get_version, tab_count, input_str) -> str: ...
def append_driver_info(
    display_init, mixer_init, get_display_driver, get_mixer_driver, input_str
) -> str: ...
def print_debug_info(
    filename: str | None = None, fileobject: FileObject | None = None
) -> None: ...
