/* Auto generated file: with make_docs.py .  Docs go in docs/reST/ref/ . */
#define DOC_IMAGE "Pygame module for image transfer."
#define DOC_IMAGE_LOAD "load(file, namehint='') -> Surface\nLoad new image from a file (or file-like object)."
#define DOC_IMAGE_LOADSIZEDSVG "load_sized_svg(file, size) -> Surface\nLoad an SVG image from a file (or file-like object) with the given size."
#define DOC_IMAGE_LOADANIMATION "load_animation(file, namehint='') -> list[tuple[Surface, int]]\nLoad an animation (GIF/WEBP) from a file (or file-like object)."
#define DOC_IMAGE_SAVE "save(surface, file, namehint='') -> None\nSave an image to file (or file-like object)."
#define DOC_IMAGE_GETSDLIMAGEVERSION "get_sdl_image_version(linked=True) -> Optional[tuple[int, int, int]]\nGet version number of the SDL_Image library being used."
#define DOC_IMAGE_GETEXTENDED "get_extended() -> bool\nTest if extended image formats can be loaded."
#define DOC_IMAGE_TOSTRING "tostring(surface, format, flipped=False, pitch=-1) -> bytes\nTransfer image to byte buffer."
#define DOC_IMAGE_TOBYTES "tobytes(surface, format, flipped=False, pitch=-1) -> bytes\nTransfer image to byte buffer."
#define DOC_IMAGE_FROMSTRING "fromstring(bytes, size, format, flipped=False, pitch=-1) -> Surface\nCreate new Surface from a byte buffer."
#define DOC_IMAGE_FROMBYTES "frombytes(bytes, size, format, flipped=False, pitch=-1) -> Surface\nCreate new Surface from a byte buffer."
#define DOC_IMAGE_FROMBUFFER "frombuffer(buffer, size, format, pitch=-1) -> Surface\nCreate a new Surface that shares data inside a bytes buffer."
#define DOC_IMAGE_LOADBASIC "load_basic(file, /) -> Surface\nLoad new BMP image from a file (or file-like object)."
#define DOC_IMAGE_LOADEXTENDED "load_extended(file, namehint='') -> Surface\nLoad an image from a file (or file-like object)."
#define DOC_IMAGE_SAVEEXTENDED "save_extended(surface, file, namehint='') -> None\nSave a png/jpg image to file (or file-like object)."
