/* Auto generated file: with make_docs.py .  Docs go in docs/reST/ref/ . */
#define DOC_KEY "Pygame module to work with the keyboard."
#define DOC_KEY_GETFOCUSED "get_focused() -> bool\nTrue if the display is receiving keyboard input from the system."
#define DOC_KEY_GETPRESSED "get_pressed() -> ScancodeWrapper\nGet the state of all keyboard buttons."
#define DOC_KEY_GETJUSTPRESSED "get_just_pressed() -> ScancodeWrapper\nReturns a ScancodeWrapper containing the most recent key presses."
#define DOC_KEY_GETJUSTRELEASED "get_just_released() -> ScancodeWrapper\nReturns a ScancodeWrapper containing the most recent key releases."
#define DOC_KEY_GETMODS "get_mods() -> int\nDetermine which modifier keys are being held."
#define DOC_KEY_SETMODS "set_mods(mods, /) -> None\nTemporarily set which modifier keys are pressed."
#define DOC_KEY_SETREPEAT "set_repeat(delay=0, interval=0, /) -> None\nControl how held keys are repeated."
#define DOC_KEY_GETREPEAT "get_repeat() -> tuple[int, int]\nSee how held keys are repeated."
#define DOC_KEY_NAME "name(key, use_compat=True) -> str\nGet the name of a key identifier."
#define DOC_KEY_KEYCODE "key_code(name) -> int\nGet the key identifier from a key name."
#define DOC_KEY_STARTTEXTINPUT "start_text_input() -> None\nStart handling Unicode text input events."
#define DOC_KEY_STOPTEXTINPUT "stop_text_input() -> None\nStop handling Unicode text input events."
#define DOC_KEY_SETTEXTINPUTRECT "set_text_input_rect(rect, /) -> None\nControls the position of the candidate list."
