/* Auto generated file: with make_docs.py .  Docs go in docs/reST/ref/ . */
#define DOC_MOUSE "Pygame module to work with the mouse."
#define DOC_MOUSE_GETPRESSED "get_pressed(num_buttons=3, desktop=False) -> tuple[bool, bool, bool]\nget_pressed(num_buttons, desktop=False) -> tuple\nGet the state of the mouse buttons."
#define DOC_MOUSE_GETJUSTPRESSED "get_just_pressed() -> tuple\nGet the most recently pressed buttons."
#define DOC_MOUSE_GETJUSTRELEASED "get_just_released() -> tuple\nGet the most recently released buttons."
#define DOC_MOUSE_GETPOS "get_pos(desktop=False) -> tuple[int, int]\nGet the mouse cursor position."
#define DOC_MOUSE_GETREL "get_rel() -> tuple[int, int]\nGet the amount of mouse movement."
#define DOC_MOUSE_SETPOS "set_pos(pos, /) -> None\nset_pos(x, y, /) -> None\nSet the mouse cursor position."
#define DOC_MOUSE_SETVISIBLE "set_visible(value, /) -> int\nHide or show the mouse cursor."
#define DOC_MOUSE_GETVISIBLE "get_visible() -> bool\nGet the current visibility state of the mouse cursor."
#define DOC_MOUSE_GETFOCUSED "get_focused() -> bool\nCheck if the display is receiving mouse input."
#define DOC_MOUSE_SETCURSOR "set_cursor(cursor) -> None\nset_cursor(size, hotspot, xormasks, andmasks) -> None\nset_cursor(hotspot, surface) -> None\nset_cursor(constant) -> None\nSet the mouse cursor to a new cursor."
#define DOC_MOUSE_GETCURSOR "get_cursor() -> Cursor\nGet the current mouse cursor."
#define DOC_MOUSE_GETRELATIVEMODE "get_relative_mode() -> bool\nQuery whether relative mouse mode is enabled."
#define DOC_MOUSE_SETRELATIVEMODE "set_relative_mode(enable, /) -> None\nSet relative mouse mode."
