/* Auto generated file: with make_docs.py .  Docs go in docs/reST/ref/ . */
#define DOC_RECT "Rect(left, top, width, height, /) -> Rect\nRect((left, top), (width, height), /) -> Rect\nRect(object, /) -> Rect\nRect() -> Rect\nFRect(left, top, width, height, /) -> FRect\nFRect((left, top), (width, height), /) -> FRect\nFRect(object, /) -> FRect\nFRect() -> FRect\nPygame object for storing rectangular coordinates."
#define DOC_RECT_COPY "copy() -> Self\nCopy the rectangle."
#define DOC_RECT_MOVE "move(x, y, /) -> Self\nmove(move_by, /) -> Self\nMoves the rectangle."
#define DOC_RECT_MOVEIP "move_ip(x, y, /) -> None\nmove_ip(move_by, /) -> None\nMoves the rectangle, in place."
#define DOC_RECT_MOVETO "move_to(**kwargs) -> Self\nMoves the rectangle to the specified position."
#define DOC_RECT_INFLATE "inflate(x, y, /) -> Self\ninflate(inflate_by, /) -> Self\nGrow or shrink the rectangle size."
#define DOC_RECT_INFLATEIP "inflate_ip(x, y, /) -> None\ninflate_ip(inflate_by, /) -> None\nGrow or shrink the rectangle size, in place."
#define DOC_RECT_SCALEBY "scale_by(x, y=...) -> Self\nscale_by(scale_by) -> Self\nScale the rectangle by given a multiplier."
#define DOC_RECT_SCALEBYIP "scale_by_ip(x, y=...) -> None\nscale_by_ip(scale_by) -> None\nGrow or shrink the rectangle size, in place."
#define DOC_RECT_UPDATE "update(left, top, width, height, /) -> None\nupdate(left_top, width_height, /) -> None\nupdate(single_arg, /) -> None\nSets the position and size of the rectangle."
#define DOC_RECT_CLAMP "clamp(rect, /) -> Self\nclamp(left_top, width_height, /) -> Self\nclamp(left, top, width, height, /) -> Self\nMoves the rectangle inside another."
#define DOC_RECT_CLAMPIP "clamp_ip(rect, /) -> None\nclamp_ip(left_top, width_height, /) -> None\nclamp_ip(left, top, width, height, /) -> None\nMoves the rectangle inside another, in place."
#define DOC_RECT_CLIP "clip(rect, /) -> Self\nclip(left_top, width_height, /) -> Self\nclip(left, top, width, height, /) -> Self\nCrops a rectangle inside another."
#define DOC_RECT_CLIPLINE "clipline(x1, x2, x3, x4, /) -> tuple\nclipline(first_point, second_point, /) -> tuple\nclipline(rect_arg, /) -> tuple\nCrops a line inside a rectangle."
#define DOC_RECT_UNION "union(rect, /) -> Self\nunion(left_top, width_height, /) -> Self\nunion(left, top, width, height, /) -> Self\nJoins two rectangles into one."
#define DOC_RECT_UNIONIP "union_ip(rect, /) -> None\nunion_ip(left_top, width_height, /) -> None\nunion_ip(left, top, width, height, /) -> None\nJoins two rectangles into one, in place."
#define DOC_RECT_UNIONALL "unionall(rect, /) -> Self\nThe union of many rectangles."
#define DOC_RECT_UNIONALLIP "unionall_ip(rect_SequenceLike, /) -> None\nThe union of many rectangles, in place."
#define DOC_RECT_FIT "fit(rect, /) -> Self\nfit(left_top, width_height, /) -> Self\nfit(left, top, width, height, /) -> Self\nResize and move a rectangle with aspect ratio."
#define DOC_RECT_NORMALIZE "normalize() -> None\nCorrect negative sizes."
#define DOC_RECT_CONTAINS "contains(rect, /) -> bool\ncontains(left_top, width_height, /) -> bool\ncontains(left, top, width, height, /) -> bool\nTest if one rectangle is inside another."
#define DOC_RECT_COLLIDEPOINT "collidepoint(x, y, /) -> bool\ncollidepoint(x_y, /) -> bool\nTest if a point is inside a rectangle."
#define DOC_RECT_COLLIDERECT "colliderect(rect, /) -> bool\ncolliderect(left_top, width_height, /) -> bool\ncolliderect(left, top, width, height, /) -> bool\nTest if two rectangles overlap."
#define DOC_RECT_COLLIDELIST "collidelist(rect_list, /) -> int\nTest if one rectangle in a list intersects."
#define DOC_RECT_COLLIDELISTALL "collidelistall(rect_list, /) -> list[int]\nTest if all rectangles in a list intersect."
#define DOC_RECT_COLLIDEOBJECTS "collideobjects(objects, key=None) -> _T | None\nTest if any object in a list intersects."
#define DOC_RECT_COLLIDEOBJECTSALL "collideobjectsall(objects, key=None) -> list[_T]\nTest if all objects in a list intersect."
#define DOC_RECT_COLLIDEDICT "collidedict(rect_dict, values=False) -> tuple[_RectTypeCompatible_co, _V] | None\ncollidedict(rect_dict, values) -> tuple[_K, _RectTypeCompatible_co] | None\nTest if one rectangle in a dictionary intersects."
#define DOC_RECT_COLLIDEDICTALL "collidedictall(rect_dict, values=False) -> list[tuple[_RectTypeCompatible_co, _V]]\ncollidedictall(rect_dict, values) -> list[tuple[_K, _RectTypeCompatible_co]]\nTest if all rectangles in a dictionary intersect."
