/* Auto generated file: with makeref.py .  Docs go in docs/reST/ref/ . */
#define DOC_WINDOW "pygame module to control windows"
#define DOC_WINDOW_GETWINDOWS "get_windows() -> Tuple[Window, ...]\ndocs_needed"
#define DOC_WINDOW_GETGRABBEDWINDOW "get_grabbed_window() -> Optional[Window]\ndocs_needed"
#define DOC_WINDOW_WINDOW "Window(title='pygame window', size=(640, 480), position=WINDOWPOS_UNDEFINED, **flags)\npygame object that represents a window"
#define DOC_WINDOW_WINDOW_FROMDISPLAYMODULE "from_display_module() -> Window\nCreate a Window object using window data from display module"
#define DOC_WINDOW_WINDOW_FROMEXISTINGWINDOW "from_existing_window(hwnd) -> Window\nCreate a Window object and embed the window to an existing window"
#define DOC_WINDOW_WINDOW_DESTROY "destroy() -> None\nDestroy the window"
#define DOC_WINDOW_WINDOW_SETWINDOWED "set_windowed() -> None\nEnable windowed mode (exit fullscreen)"
#define DOC_WINDOW_WINDOW_SETFULLSCREEN "set_fullscreen(desktop=False) -> None\nEnter fullscreen"
#define DOC_WINDOW_WINDOW_FOCUS "focus(input_only=False) -> None\nSet the window to be focused"
#define DOC_WINDOW_WINDOW_HIDE "hide() -> None\nHide the window"
#define DOC_WINDOW_WINDOW_SHOW "show() -> None\nShow the window"
#define DOC_WINDOW_WINDOW_RESTORE "restore() -> None\nRestore the size and position of a minimized or maximized window"
#define DOC_WINDOW_WINDOW_MAXIMIZE "maximize() -> None\nMaximize the window"
#define DOC_WINDOW_WINDOW_MINIMIZE "minimize() -> None\nMinimize the window"
#define DOC_WINDOW_WINDOW_FLASH "flash(briefly=False) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_FLASHCANCEL "flash_cancel() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETMODALFOR "set_modal_for(parent) -> None\nSet the window as a modal for a parent window"
#define DOC_WINDOW_WINDOW_UPDATEFROMSURFACE "update_from_surface(*rects) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETGRAB "set_grab(enable) -> None\nSet the window's input grab state"
#define DOC_WINDOW_WINDOW_GETGRAB "get_grab() -> bool\nGet the window's input grab state"
#define DOC_WINDOW_WINDOW_SETALWAYSONTOP "set_always_on_top(enable) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETALWAYSONTOP "get_always_on_top() -> bool\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETTITLE "set_title(title) -> None\nSet the window title"
#define DOC_WINDOW_WINDOW_GETTITLE "get_title() -> str\nGet the window title"
#define DOC_WINDOW_WINDOW_SETRESIZABLE "set_resizable(enable) -> None\nSet whether the window is resizable"
#define DOC_WINDOW_WINDOW_GETRESIZABLE "get_resizable() -> bool\nGet whether the window is resizable"
#define DOC_WINDOW_WINDOW_SETBORDERLESS "set_borderless(enable) -> None\nSet whether the window is borderless"
#define DOC_WINDOW_WINDOW_GETBORDERLESS "get_borderless() -> bool\nGet whether the window is borderless"
#define DOC_WINDOW_WINDOW_SETSIZE "set_size((width, height)) -> None\nSet the window size"
#define DOC_WINDOW_WINDOW_GETSIZE "get_size() -> (width, height)\nGet the window size"
#define DOC_WINDOW_WINDOW_SETPOSITION "set_position((x, y)) -> None\nSet the window's screen position"
#define DOC_WINDOW_WINDOW_GETPOSITION "get_position() -> (x, y)\nGet the window's screen position"
#define DOC_WINDOW_WINDOW_SETOPACITY "set_opacity(opacity) -> None\nSet the window opacity"
#define DOC_WINDOW_WINDOW_GETOPACITY "get_opacity() -> float\nGet the window opacity"
#define DOC_WINDOW_WINDOW_SETICON "set_icon(icon) -> None\nSet the icon for the window"
#define DOC_WINDOW_WINDOW_GETDISPLAYINDEX "get_display_index() -> int\nGet the index of the display that owns the window"
#define DOC_WINDOW_WINDOW_GETSURFACE "get_surface() -> Surface\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETWINDOWID "get_window_id() -> int\nGet the unique window ID"
#define DOC_WINDOW_WINDOW_GETFOREIGN "get_foreign() -> bool\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETWMINFO "get_wm_info() -> dict\ndocs_needed"
