/* Auto generated file: with makeref.py .  Docs go in docs/reST/ref/ . */
#define DOC_WINDOW "pygame module to control windows"
#define DOC_WINDOW_GETWINDOWS "get_windows() -> Tuple[Window, ...]\ndocs_needed"
#define DOC_WINDOW_GETGRABBEDWINDOW "get_grabbed_window() -> Optional[Window]\ndocs_needed"
#define DOC_WINDOW_WINDOW "Window(title='pygame window', size=(640, 480), position=WINDOWPOS_UNDEFINED, **flags)\ndocs_needed"
#define DOC_WINDOW_WINDOW_FROMDISPLAYMODULE "from_display_module() -> Window\ndocs_needed"
#define DOC_WINDOW_WINDOW_FROMEXISTINGWINDOW "from_existing_window(hwnd) -> Window\ndocs_needed"
#define DOC_WINDOW_WINDOW_DESTROY "destroy() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETWINDOWED "set_windowed() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETFULLSCREEN "set_fullscreen(desktop=False) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_FOCUS "focus(input_only=False) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_HIDE "hide() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_SHOW "show() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_RESTORE "restore() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_MAXIMIZE "maximize() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_MINIMIZE "minimize() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_FLASH "flash(briefly=False) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_FLASHCANCEL "flash_cancel() -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETMODALFOR "set_modal_for(parent) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_UPDATEFROMSURFACE "update_from_surface(*rects) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETGRAB "set_grab(enable) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETGRAB "get_grab() -> bool\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETALWAYSONTOP "set_always_on_top(enable) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETALWAYSONTOP "get_always_on_top() -> bool\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETTITLE "set_title(title) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETTITLE "get_title() -> str\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETRESIZABLE "set_resizable(enable) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETRESIZABLE "get_resizable() -> bool\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETBORDERLESS "set_borderless(enable) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETBORDERLESS "get_borderless() -> bool\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETSIZE "set_size((width, height)) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETSIZE "get_size() -> (width, height)\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETPOSITION "set_position((x, y)) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETPOSITION "get_position() -> (x, y)\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETOPACITY "set_opacity(opacity) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETOPACITY "get_opacity() -> float\ndocs_needed"
#define DOC_WINDOW_WINDOW_SETICON "set_icon(icon) -> None\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETDISPLAYINDEX "get_display_index() -> int\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETSURFACE "get_surface() -> Surface\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETWINDOWID "get_window_id() -> int\ndocs_needed"
#define DOC_WINDOW_WINDOW_GETWMINFO "get_wm_info() -> dict\ndocs_needed"
