/* Auto generated file: with makeref.py .  Docs go in docs/reST/ref/ . */
#define DOC_WINDOW "pygame module to control windows"
#define DOC_WINDOW_GETGRABBEDWINDOW "get_grabbed_window() -> Optional[Window]\nGet the current grabbed window"
#define DOC_WINDOW_WINDOW "Window(title='pygame window', size=(640, 480), position=WINDOWPOS_UNDEFINED, **flags)\npygame object that represents a window"
#define DOC_WINDOW_WINDOW_FROMDISPLAYMODULE "from_display_module() -> Window\nCreate a Window object using window data from display module"
#define DOC_WINDOW_WINDOW_DESTROY "destroy() -> None\nDestroy the window"
#define DOC_WINDOW_WINDOW_SETWINDOWED "set_windowed() -> None\nEnable windowed mode (exit fullscreen)"
#define DOC_WINDOW_WINDOW_SETFULLSCREEN "set_fullscreen(desktop=False) -> None\nEnter fullscreen"
#define DOC_WINDOW_WINDOW_FOCUS "focus(input_only=False) -> None\nSet the window to be focused"
#define DOC_WINDOW_WINDOW_HIDE "hide() -> None\nHide the window"
#define DOC_WINDOW_WINDOW_SHOW "show() -> None\nShow the window"
#define DOC_WINDOW_WINDOW_RESTORE "restore() -> None\nRestore the size and position of a minimized or maximized window"
#define DOC_WINDOW_WINDOW_MAXIMIZE "maximize() -> None\nMaximize the window"
#define DOC_WINDOW_WINDOW_MINIMIZE "minimize() -> None\nMinimize the window"
#define DOC_WINDOW_WINDOW_SETMODALFOR "set_modal_for(parent) -> None\nSet the window as a modal for a parent window"
#define DOC_WINDOW_WINDOW_SETICON "set_icon(icon) -> None\nSet the icon for the window"
