name: 🐛 Guided Bug Report Form
labels: ["bug"]
description: A template to help you create a bug report to improve Pygame! Useful if this is your first time reporting an issue.
title: "[BUG] <title>"
body:
  - type: markdown
    attributes:
      value: "## Thank you for reporting an issue!"

  - type: checkboxes
    attributes:
      label: Does an issue for this already exist?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
        - label: I have ensured my environment (operating system, pygame-ce version, etc) is up to date
          required: true

  - type: markdown
    id: debug-info
    attributes:
      value: |
        If possible, please include the output of `pygame.print_debug_info()`
        from your program in your bug report. It looks something like this:

        ```
        pygame-ce 6.7.4 (SDL 2.30.3, Python 3.11.1)
        Platform:		Windows-10-10.0.22631-SP0
        System:			Windows
        System Version:	10.0.22631
        Processor:		AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
        Architecture:	Bits: 64bit	Linkage: WindowsPE

        Python:			    CPython 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
        pygame version:		2.5.0.dev3
        SDL versions:		Linked: 2.30.3	Compiled: 2.30.3
        SDL Mixer versions:	Linked: 2.8.0	Compiled: 2.8.0
        SDL Font versions:	Linked: 2.22.0	Compiled: 2.22.0
        SDL Image versions:	Linked: 2.8.2	Compiled: 2.8.2
        Freetype versions:	Linked: 2.11.1	Compiled: 2.11.1

        Display Driver:		windows
        Mixer Driver:		wasapi
        ```

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Output of `pygame.print_debug_info()` from your program. (N/A Otherwise)
      placeholder: |
        pygame-ce 6.7.4 (SDL 2.30.3, Python 3.11.1)
        Platform:		Windows-10-10.0.22631-SP0
        System:			Windows
        System Version:	10.0.22631
        Processor:		AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
        Architecture:	Bits: 64bit	Linkage: WindowsPE

        Python:			    CPython 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
        pygame version:		2.5.0.dev3
        SDL versions:		Linked: 2.30.3	Compiled: 2.30.3
        SDL Mixer versions:	Linked: 2.8.0	Compiled: 2.8.0
        SDL Font versions:	Linked: 2.22.0	Compiled: 2.22.0
        SDL Image versions:	Linked: 2.8.2	Compiled: 2.8.2
        Freetype versions:	Linked: 2.11.1	Compiled: 2.11.1

        Display Driver:		windows
        Mixer Driver:		wasapi
    validations:
      required: true

  - type: markdown
    id: other-details
    attributes:
      value: |
        If you can't get the debug output, any of the environment details included in it that you do know would be useful in diagnosing the issue & helping you.

        Other environment details, not included in `print_debug_info()`, that might help:

  - type: textarea
    id: hardware
    attributes:
      label: Relevant Hardware
      description: (e.g. if reporting a bug about a controller, tell us the brand & name of it)

  - type: textarea
    id: description
    attributes:
      label: Current behaviour
      description: Please describe the issue as clearly as you can.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Please describe what you expect to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Paste or attach any relevant screenshots or videos here.

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
        If the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment.)
      placeholder: |
        1. First I install...
        2. Then I run...
        3. Next I click...
        ...
    validations:
      required: true

  - type: textarea
    id: test-code
    attributes:
      label: Test Code
      description: If possible add a simple test program that shows the problem described in this report.
      placeholder: |
        import pygame
        pygame.init()
        print("Hello, world")
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (Stack Trace, Error Output, Other Error Logs)
      description: Paste or attach any relevant logs or errors here.
      render: shell

  - type: checkboxes
    id: self-service
    attributes:
      label: Self-service
      description:
      options:
        - label: I'd be willing to fix this issue myself.
