# This workflow generates C code tests
# Note that for intrinsics, it only runs what gets compiled
# and would naturally run. It also is limited to what can run in
# a CI environment
# IMPORTANT: binaries are not to be uploaded from this workflow!

name: Ubuntu ctest

# Run CI only on changes to main branch, or any PR to main.
# Do not run CI on any other branch. Also, skip any non-source changes
# from running on CI
on:
  push:
    branches: main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '.gitignore'
      - '*.rst'
      - '*.md'
      - '.github/workflows/*.yml'
      # only care about c code that changes
      - 'src_py/**'
      # re-include current file to not be excluded
      - '!.github/workflows/build-ubuntu-ctest.yml'

  pull_request:
    branches: main
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - '.gitignore'
      - '*.rst'
      - '*.md'
      - '.github/workflows/*.yml'
      # only care about c code that changes
      - 'src_py/**'
      # re-include current file to not be excluded
      - '!.github/workflows/build-ubuntu-ctest.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ubuntu-ctest
  cancel-in-progress: true

jobs:
  gen_ctest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        os: [ubuntu-24.04]

    env:
      # Pip now forces us to either make a venv or set this flag, so we will do
      # this
      PIP_BREAK_SYSTEM_PACKAGES: 1
      # We are using dependencies installed from apt
      PG_DEPS_FROM_SYSTEM: 1

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Install deps
      # https://github.com/actions/runner-images/issues/7192
      # https://github.com/orgs/community/discussions/47863
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev python3-dev -y

    - name: Build with the ctest suite
      id: build
      run: |
        python3 -m pip install . -Csetup-args="-Dctest=true" --break-system-packages

    - name: Run tests
      env:
        SDL_VIDEODRIVER: "dummy"
        SDL_AUDIODRIVER: "disk"
      run: python3 -m pygame.tests -v --exclude opengl,music,timing --time_out 300

    # We upload the generated files under github actions assets
    - name: Upload ctest log
      if: !cancelled()
      uses: actions/upload-artifact@v4
      with:
        name: ctest_suite_log
        path: ctest.log
