name: python3 setup.py lint

# Run lint CI on changes to main branch, or any PR to main. Do not run CI on
# any other branch.
# Run only if there are changes on files that are linted (C, Python and rst files)
on:
  push:
    branches: main
    paths:
      - '**.h'
      - '**.c'
      - '**.py'
      - '**.rst'
      - '.pre-commit-config.yaml'

  pull_request:
    branches: main
    paths:
      - '**.h'
      - '**.c'
      - '**.py'
      - '**.rst'
      - '.pre-commit-config.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-format-lint
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1

  format-lint-code-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Install deps
        run: python3 -m pip install pylint sphinx"<7.2.0"

      - name: Check code linting
        run: pylint src_py docs

      - name: Check docs changes are checked in
        run: |
          python3 buildconfig/make_docs.py
          if [[ `git status --porcelain` ]]; then
            echo "Generating docs caused changes. Please check them in."
            echo "You may need to run: python3 buildconfig/make_docs.py full_generation"
            # Run git status again, so people can see what changed.
            git status --porcelain
            exit 1
          fi
