name: PyPI Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release-pypi
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Pull all release assets
        uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1.13
        with:
          releaseId: ${{ github.event.release.id }}
          fileName: "*"
          tarBall: false
          zipBall: false
          out-file-path: "dist"

      - name: Verify release attestation
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for fname in dist/*; do
            if [[ "$fname" != *.whl && "$fname" != *.tar.gz ]]; then
              rm "$fname"
              echo "[DELETED non-python-artifact] $fname"
              continue
            fi
            if gh attestation verify $fname -R ${{ github.repository }}; then
              echo "[ALLOWED] $fname"
            else
              rm "$fname"
              echo "[DELETED failed-attestation] $fname"
            fi
          done

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
