name: Draft Github Release

on:
  push:
    branches: 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-gh-draft
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  manylinux:
    uses: ./.github/workflows/build-manylinux.yml

  macos:
    uses: ./.github/workflows/build-macos.yml

  windows:
    uses: ./.github/workflows/build-windows.yml

  sdist:
    uses: ./.github/workflows/build-ubuntu-sdist.yml

  draft-release:
    needs: [manylinux, macos, windows, sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: pygame-wheels
          pattern: pygame-wheels-*
          merge-multiple: true

      # Strips 'release/' from the ref_name, this helps us access the version
      # name as 'steps.ver.outputs.VER'
      - name: Get version
        id: ver
        run: echo "VER=${GITHUB_REF_NAME#'release/'}" >> $GITHUB_OUTPUT

      - name: Generate release attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: "pygame-wheels/*"

      - name: Draft a release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          draft: true
          prerelease: ${{ contains(steps.ver.outputs.VER, 'dev') }}
          files: pygame-wheels/*
          name: '${{ steps.ver.outputs.VER }} - {TODO put a title here} [DRAFTED BY CI]'
          tag_name: ${{ steps.ver.outputs.VER }}
          target_commitish: ${{ github.ref_name }}
          generate_release_notes: true
